In [1]:
import numpy as np

def generate_echelon_form(M):
    m = np.array(M, dtype="float64")
#     print("M: ", m)

    row, col = m.shape
#     print("row, col: ", row, col)

    new_rowlist = []
    rows_left = set(range(row))
#     print("rows_loft: ", rows_left)
    
    for c in range(col):
        rows_with_nonzero = [r for r in rows_left if m[r][c] != 0]
#         print("rows_with_nonzero: ", rows_with_nonzero)
        
        if rows_with_nonzero != []:
            pivot = rows_with_nonzero[0]
#             print("pivot", pivot)
            
            new_rowlist.append(m[pivot])
#             print("new_rowlist: ", new_rowlist)

            rows_left.remove(pivot)
#             print("rows_left: ", rows_left)

            for r in rows_with_nonzero[1:]:
                multiplier = m[r][c] / m[pivot][c]
#                 print("multiplier: ", multiplier)

                m[r] -= multiplier * m[pivot]

#             print("rows_left: ", rows_left)
    
    return np.matrix(new_rowlist)

M = [[0, 2, 3, 4, 5], [0, 0, 0, 3, 2], [1, 2, 3, 4, 5], [0, 0, 0, 6, 7], [0, 0, 0, 9, 9]]
    
print("Echelon form: ", generate_echelon_form(M))

Echelon form:  [[ 1.  2.  3.  4.  5.]
 [ 0.  2.  3.  4.  5.]
 [ 0.  0.  0.  3.  2.]
 [ 0.  0.  0.  0.  3.]]
