In [1]:
import source as sc
import numpy as np

def direct_sum_decompose(U_basis, V_basis, w):
    U_basis_vec = np.array(U_basis)
    V_basis_vec = np.array(V_basis)
    joined_list = np.vstack((U_basis_vec, V_basis_vec))
    u_vec = np.zeros(U_basis_vec[0].shape)
    v_vec = np.zeros(V_basis_vec[0].shape)
#     print(joined_list)
    
    A = np.transpose(np.array(joined_list))
    b = np.array(w)
    vec = sc.solve(A, b)[0]
#     print(vec)
    
    for (idx, a) in enumerate(vec):
#         print(idx, a)
        if (joined_list[idx].tolist() in U_basis):
#             print(u_vec)
            u_vec = u_vec + (a * joined_list[idx])
#             print(u_vec)
        elif (joined_list[idx].tolist() in V_basis):
#             print(v_vec)
            v_vec = v_vec + (a * joined_list[idx])
#             print(v_vec)
#     print(u_vec, v_vec)
    return u_vec, v_vec


In [2]:
U_basis = [[2,1,0,0,6,0],[11,5,0,0,1,0],[3,1.5,0,0,7.5,0]]
V_basis = [[0,0,7,0,0,1],[0,0,15,0,0,2]]

In [3]:
w = [2,5,0,0,1,0]
print(direct_sum_decompose(U_basis, V_basis, w))

(array([ 2.,  5.,  0.,  0.,  1.,  0.]), array([ 0.,  0.,  0.,  0.,  0.,  0.]))


In [4]:
w = [0,0,3,0,0,-4]
print(direct_sum_decompose(U_basis, V_basis, w))

(array([ 0.,  0.,  0.,  0.,  0.,  0.]), array([ 0.,  0.,  3.,  0.,  0., -4.]))


In [5]:
w = [1,2,0,0,2,1]
print(direct_sum_decompose(U_basis, V_basis, w))

(array([ 1.,  2.,  0.,  0.,  2.,  0.]), array([  0.00000000e+00,   0.00000000e+00,  -2.84217094e-14,
         0.00000000e+00,   0.00000000e+00,   1.00000000e+00]))


In [6]:
w = [-6,2,4,0,4,5]
print(direct_sum_decompose(U_basis, V_basis, w))

(array([-6.,  2.,  0.,  0.,  4.,  0.]), array([ 0.,  0.,  4.,  0.,  0.,  5.]))
