In [1]:
import source as sc
import numpy as np

def find_triangular_matrix_invese(A):
    I = np.identity(sc.rank(A)).tolist()
#     print(I)
    
    B_vec = None
    
    for idx in range(len(A)) :
#         print(triangular_solve(A, I[idx]))

        t_solve = triangular_solve(A, I[idx])
        if idx != 0:
            B_vec = np.vstack((B_vec, t_solve))
        else:
            B_vec = t_solve

    return np.transpose(np.asmatrix(B_vec))

def triangular_solve(rowlist, b):
    rows = np.array(rowlist)
    x = np.zeros(rows[0].shape)
#     print(rows, x)
    
    for j in reversed(range(len(rows))):
        row = rowlist[j]
#         print(b[j], np.dot(x, row), row[j])
        x[j] = (b[j] - np.dot(x, row)) / row[j]
    return x

In [2]:
triangular_solve([[1,0.5,-2,4],[0,3,3,2],[0,0,1,5],[0,0,0,2]],[-8,3,-4,6])

array([-67.,  18., -19.,   3.])

In [3]:
A = [[1,0.5,-2,4],[0,3,3,2],[0,0,1,5],[0,0,0,2]]
B = find_triangular_matrix_invese(A)

In [4]:
print(np.matrix(A) * B)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   8.88178420e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
