In [2]:
import numpy as np

In [65]:
def project_along(b, v):
    b_vec = np.array(b, dtype=np.float64)
    v_vec = np.array(v, dtype=np.float64)
    sigma = (np.dot(b,v)/np.dot(v,v)) if np.dot(v,v) > 1e-20 else 0
    return sigma * v_vec

In [44]:
b = [1,2,2]
v1 = [1,2,1]
v2 = [-1,0,1]
vlist = [v1, v2]

In [45]:
project_along(b, v1)

array([ 1.16666667,  2.33333333,  1.16666667])

In [59]:
def project_orthogonal(b, vlist):
    for v in vlist:
        b = b - project_along(b, v)
    return np.array(b)

In [47]:
project_orthogonal(b, vlist)

array([ 0.33333333, -0.33333333,  0.33333333])

In [105]:
def aug_project_othogonal(b, vlist):
#     sigmadict = {len(vlist) : 1} # bk => k:1
    sigma_vec = [1 if i == len(vlist) else 0 for i in range(len(vlist) + 1)]
    b_vec = np.array(b, dtype=np.float64)
    
    for i,v in enumerate(vlist):
        v_vec = np.array(v, dtype=np.float64)
        sigma = (np.dot(b,v)/np.dot(v,v)) if np.dot(v,v) > 1e-20 else 0
#         sigmadict[i] = sigma
        sigma_vec[i] = sigma
        b_vec = b_vec - sigma * v_vec
    return (b_vec, sigma_vec)

In [96]:
aug_project_othogonal(b, vlist)

(array([-8. ,  0.5, -3.5]), [0.75, 0.5, 1.0, 1])

In [50]:
def orthogonalize(vlist):
    vstarlist = []
    for v in vlist:
        vstarlist.append(project_orthogonal(v, vstarlist))
    return vstarlist

In [51]:
vlist = [[2,0,0], [1,2,2], [1,0,2]]

In [52]:
orthogonalize(vlist)

[array([2, 0, 0]), array([ 0.,  2.,  2.]), array([ 0., -1.,  1.])]

In [53]:
vlist = [[1,0,2], [1,0,2], [2,0,0]]

In [61]:
orthogonalize(vlist)

[array([1, 0, 2]), array([ 0.,  0.,  0.]), array([ 1.6,  0. , -0.8])]

In [62]:
vlist = [[2,0,0], [1,2,2], [1,0,2]]

In [67]:
orthogonalize(vlist)

[array([2, 0, 0]), array([ 0.,  2.,  2.]), array([ 0., -1.,  1.])]

In [71]:
# method 1
vlist = [[8,-2,2], [4,2,4]]
b = [5,-5,2]

In [72]:
orthogonalize(vlist)

[array([ 8, -2,  2]), array([ 0.,  3.,  3.])]

In [75]:
project_orthogonal(b, orthogonalize(vlist))

array([-1., -2.,  2.])

In [78]:
# method 2
vlist = [[8,-2,2], [4,2,4], [5,-5,2]]

In [80]:
orthogonalize(vlist)

[array([ 8, -2,  2]), array([ 0.,  3.,  3.]), array([-1., -2.,  2.])]

In [110]:
def aug_orthogonalize(vlist):
    vstarlist = []
    sigma_vecs = []
    for v in vlist:
        (vstar, sigma_vec) = aug_project_othogonal(v, vstarlist)
        vstarlist.append(vstar)
        sigma_vecs.append(np.array([sigma_vec[i] if i < len(sigma_vec) else 0 for i in range(len(vlist))]))
    return vstarlist, sigma_vecs

In [111]:
vlist = [[2,0,0], [1,2,2], [1,0,2]]
aug_orthogonalize(vlist)

([array([ 2.,  0.,  0.]), array([ 0.,  2.,  2.]), array([ 0., -1.,  1.])],
 [array([1, 0, 0]), array([ 0.5,  1. ,  0. ]), array([ 0.5,  0.5,  1. ])])