In [2]:
import numpy as np

In [6]:
def project_along(b, v):
    b_vec = np.array(b, dtype=np.float64)
    v_vec = np.array(v, dtype=np.float64)
    sigma = (np.dot(b,v)/np.dot(v,v)) if np.dot(v,v) > 1e-20 else 0
    return sigma * v_vec

In [15]:
b = [1,2,2]
v1 = [1,2,1]
v2 = [-1,0,1]
vlist = [v1, v2]

In [12]:
project_along(b, v1)

array([ 1.16666667,  2.33333333,  1.16666667])

In [16]:
def project_orthogonal(b, vlist):
    for v in vlist:
        b = b - project_along(b, v)
    return b

In [17]:
project_orthogonal(b, vlist)

array([ 0.33333333, -0.33333333,  0.33333333])

In [19]:
def aug_project_othogonal(b, vlist):
    sigmadict = {len(vlist) : 1} # bk => k:1
    b_vec = np.array(b, dtype=np.float64)
    
    for i,v in enumerate(vlist):
        v_vec = np.array(v, dtype=np.float64)
        sigma = (np.dot(b,v)/np.dot(v,v)) if np.dot(v,v) > 1e-20 else 0
        sigmadict[i] = sigma
        b_vec = b_vec - sigma * v_vec
    return (b_vec, sigmadict)

In [20]:
aug_project_othogonal(b, vlist)

(array([ 0.33333333, -0.33333333,  0.33333333]),
 {0: 1.1666666666666667, 1: 0.5, 2: 1})