# ML lab 04-2: TensorFlow로 파일에서 데이타 읽어오기 (new)


## Queue Runner

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  7070.98 
Prediction:
 [[ 235.2278595 ]
 [ 282.40145874]
 [ 278.3961792 ]
 [ 303.915802  ]
 [ 214.6239624 ]
 [ 159.15426636]
 [ 228.53509521]
 [ 170.92645264]
 [ 264.6505127 ]
 [ 246.59117126]]
10 Cost:  5.57778 
Prediction:
 [[ 154.65846252]
 [ 185.55497742]
 [ 182.97674561]
 [ 199.99612427]
 [ 140.76089478]
 [ 104.69593048]
 [ 150.7492981 ]
 [ 113.26345825]
 [ 174.13757324]
 [ 162.75192261]]
20 Cost:  4.62938 
Prediction:
 [[ 154.11100769]
 [ 184.9029541 ]
 [ 182.33100891]
 [ 199.2953949 ]
 [ 140.26301575]
 [ 104.33344269]
 [ 150.22685242]
 [ 112.87885284]
 [ 173.53265381]
 [ 162.19769287]]
30 Cost:  4.61896 
Prediction:
 [[ 154.10362244]
 [ 184.90007019]
 [ 182.32485962]
 [ 199.29121399]
 [ 140.26023865]
 [ 104.33596039]
 [ 150.2257843 ]
 [ 112.88076019]
 [ 173.53443909]
 [ 162.20545959]]
40 Cost:  4.61284 
Prediction:
 [[ 154.09985352]
 [ 184.90151978]
 [ 182.32302856]
 [ 199.29171753]
 [ 140.26077271]
 [ 104.34093475]
 [ 150.22822571]
 [ 112.88526917]
 [ 173.5402832 ]
 [ 1