# ML lab 04-1: multi-variable linear regression을 TensorFlow에서 구현하기 (new)

## Matrix

$$ \left. \begin{pmatrix} x_1 & x_2 & x_3 \end{pmatrix} \cdot \begin{pmatrix} w_1 \\ w_2 \\ w_3 \end{pmatrix} = (x_1w_1 + x_2w_2 + x_3w_3) \right. $$

$$ H(X) = XW $$

In [1]:
import tensorflow as tf

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  147043.0 
Prediction:
 [[-187.61991882]
 [-225.16479492]
 [-222.14205933]
 [-241.60574341]
 [-171.72393799]]
10 Cost:  2.77347 
Prediction:
 [[ 151.59158325]
 [ 182.54949951]
 [ 179.58198547]
 [ 195.86186218]
 [ 139.26106262]]
20 Cost:  1.42155 
Prediction:
 [[ 152.61404419]
 [ 183.78578186]
 [ 180.79629517]
 [ 197.18441772]
 [ 140.20571899]]
30 Cost:  1.41577 
Prediction:
 [[ 152.61326599]
 [ 183.79219055]
 [ 180.79881287]
 [ 197.18736267]
 [ 140.21226501]]
40 Cost:  1.41 
Prediction:
 [[ 152.60942078]
 [ 183.79489136]
 [ 180.79768372]
 [ 197.18630981]
 [ 140.21598816]]
50 Cost:  1.40427 
Prediction:
 [[ 152.60554504]
 [ 183.79756165]
 [ 180.79652405]
 [ 197.1852417 ]
 [ 140.21968079]]
60 Cost:  1.39858 
Prediction:
 [[ 152.60171509]
 [ 183.80023193]
 [ 180.79537964]
 [ 197.18418884]
 [ 140.22335815]]
70 Cost:  1.3929 
Prediction:
 [[ 152.59785461]
 [ 183.8028717 ]
 [ 180.79421997]
 [ 197.18312073]
 [ 140.22703552]]
80 Cost:  1.38728 
Prediction:
 [[ 152.59402466]
 [ 183.8055