# ML lab 04-1: multi-variable linear regression을 TensorFlow에서 구현하기 (new)

## Setup

In [1]:
import tensorflow as tf

## Hypothesis using matrix

$$ H(x_1, x_2, x_3) = x_1w_1 + x_1w_2 + x_1w_3 $$

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  36362.7 
Prediction:
 [-13.43817997 -21.87608719 -18.72015381 -18.32820129 -19.92545319]
10 Cost:  18.3743 
Prediction:
 [ 155.19248962  180.83360291  180.99856567  199.16134644  134.6973114 ]
20 Cost:  17.9574 
Prediction:
 [ 155.68788147  181.4571991   181.59840393  199.81539917  135.17922974]
30 Cost:  17.8738 
Prediction:
 [ 155.67459106  181.46929932  181.59579468  199.81343079  135.19473267]
40 Cost:  17.7906 
Prediction:
 [ 155.6598053   181.47952271  181.59135437  199.8094635   135.20878601]
50 Cost:  17.7078 
Prediction:
 [ 155.64505005  181.48971558  181.58694458  199.80551147  135.22280884]
60 Cost:  17.6255 
Prediction:
 [ 155.63034058  181.49989319  181.58253479  199.80157471  135.23678589]
70 Cost:  17.5437 
Prediction:
 [ 155.61567688  181.51002502  181.578125    199.79762268  135.25071716]
80 Cost:  17.4622 
Prediction:
 [ 155.6010437   181.52009583  181.57373047  199.79367065  135.26461792]
90 Cost:  17.3812 
Prediction:
 [ 155.5864563   181.53018188  181.5693