In [1]:
import numpy as np

In [2]:
def solve (a, b):
    return np.linalg.lstsq(a, b) if isinstance(a, int) else np.linalg.lstsq(a, b)

In [3]:
zero_like = 1e-14

In [4]:
a = np.array([[3,1], [1,2]])

In [5]:
b = np.array([9,8])

In [6]:
solve(a,b)

(array([ 2.,  3.]),
 array([], dtype=float64),
 2,
 array([ 3.61803399,  1.38196601]))

In [7]:
A = np.transpose(np.array([[0,1,0,0],[0,0,1,0],[1,0,3,0]]))

In [8]:
b = np.array([1,0,0,0])

In [9]:
u = np.transpose(np.array([solve(A,b)[0]]))

In [10]:
print(A)

[[0 0 1]
 [1 0 0]
 [0 1 3]
 [0 0 0]]


In [11]:
print(u)

[[ 0.]
 [-3.]
 [ 1.]]


In [12]:
print(np.asmatrix(A)*np.asmatrix(u))

[[  1.00000000e+00]
 [  0.00000000e+00]
 [  2.22044605e-16]
 [  0.00000000e+00]]


In [13]:
print(np.transpose(np.asmatrix(b)))

[[1]
 [0]
 [0]
 [0]]


In [14]:
residual = np.squeeze(np.asarray((np.transpose(np.asmatrix(b)) - np.asmatrix(A)*np.asmatrix(u))))

In [15]:
print(residual)

[  2.22044605e-16   0.00000000e+00  -2.22044605e-16   0.00000000e+00]


In [16]:
print(np.dot(residual, residual))

9.86076131526e-32


In [17]:
print(np.dot(residual, residual) < zero_like)

True


In [18]:
def is_superfluous(L, i):
    zero_like = 1e-14
    A = np.transpose(np.array(L[:i] + L[i+1:]))
    b = np.array(L[i])
    u = np.transpose(np.array([solve(A,b)[0]]))
    
    residual = np.squeeze(np.asarray((np.transpose(np.asmatrix(b)) - np.asmatrix(A)*np.asmatrix(u))))
    return np.dot(residual, residual) < zero_like

In [19]:
is_superfluous([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,3,0]], 1)

False

In [20]:
is_superfluous([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,3,0]], 2)

True

In [21]:
is_superfluous([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,3,0]], 3)

True